
server:
  port: 2222
  
spring:
  boot:
    admin:
      client:
        url: "http://localhost:9090/"
  application:
    name:      "25-Greet-API"   
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        



